[build]
command = "CI=false npm install --legacy-peer-deps && CI=false npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "16.20.0"
VITE_CJS_IGNORE_WARNING = "true"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200 